import Link from "next/link";
import LogoMarquee from "@/components/LogoMarquee";

const trustLogos = [
  { src: "/lp/logo-blogseo.png", alt: "BlogSEO" },
  { src: "/lp/logo-lemlist.png", alt: "lemlist" },
  { src: "/lp/logo-folk.png", alt: "folk" },
  { src: "/lp/logo-leadbay.png", alt: "Leadbay" },
  { src: "/lp/logo-ringover.png", alt: "Ringover" },
  { src: "/lp/logo-attio.jpg", alt: "Attio" },
  { src: "/lp/logo-lagrowthmachine.png", alt: "La Growth Machine" },
  { src: "/lp/logo-gojiberry.png", alt: "gojiberry" },
  { src: "/lp/logo-chatseo.png", alt: "ChatSEO" },
  { src: "/lp/logo-abyssale.png", alt: "Abyssale" },
];

export default function Hero() {
  return (
    <section className="relative overflow-hidden bg-[#c5ebfd]">
      <img
        src="/lp/hero-clouds-cotton-blue-v7.png"
        alt=""
        aria-hidden
        className="lp-cloud-image pointer-events-none absolute inset-x-0 bottom-0 w-full select-none object-cover"
      />

      <div className="relative mx-auto flex min-h-[936px] max-w-[980px] flex-col items-center px-[84px] pb-[60px] pt-[103px] text-center">
        <div className="flex items-center gap-[10px] rounded-full border border-white bg-white px-[14px] py-[9px] pr-[18px] shadow-[0_4px_14px_0_rgba(42,73,117,0.055)]">
          <svg width="15" height="15" viewBox="0 0 24 24" fill="#76badd" aria-hidden>
            <circle cx="12" cy="12" r="7" />
            <circle cx="12" cy="5" r="3" />
          </svg>
          <span className="text-[15px] font-medium text-ink">Where B2B brands work with creators</span>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#17181c" strokeWidth="2" strokeLinecap="round" aria-hidden>
            <path d="M5 12h14M13 6l6 6-6 6" />
          </svg>
        </div>

        <h1 className="mt-10 font-display text-[77px] font-semibold leading-[80.85px] tracking-[-3.08px] text-ink">
          The B2B LinkedIn
          <br />
          Creator Marketplace.
        </h1>

        <p className="mt-[30px] max-w-[568px] text-balance text-[21px] leading-[31.5px] text-[#43454c]">
          Find the creators your buyers already trust, launch campaigns in
          days, and track the clicks, leads and pipeline generated by every
          post.
        </p>

        <div className="mt-[44px] flex items-center gap-6">
          <Link
            href="/register"
            className="lp-hero-primary flex items-center gap-[11px] rounded-[12px] bg-ink px-[28px] py-[16px] text-[16px] font-semibold text-white transition-colors hover:bg-black"
          >
            Launch a campaign
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M7 17L17 7M9 7h8v8" />
            </svg>
          </Link>
          <Link
            href="/#how-it-works"
            className="lp-hero-secondary flex items-center gap-[9px] text-[16.5px] font-semibold text-ink"
          >
            See how Naano works
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M5 12h14M13 6l6 6-6 6" />
            </svg>
          </Link>
        </div>

        <div className="mt-[34px] flex items-center gap-[11px] text-[16px] text-[#55575e]">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden>
            <path d="M12 2l2.4 7.2H22l-6 4.5 2.2 7.3-6.2-4.4-6.2 4.4 2.2-7.3-6-4.5h7.6z" />
          </svg>
          Trusted by modern B2B teams
        </div>

        <div className="mt-[48px] w-full">
          <LogoMarquee imgs={trustLogos} leadingLabel="CASE STUDY" />
        </div>
      </div>
    </section>
  );
}