import Link from "next/link";
import LogoMarquee from "@/components/LogoMarquee";

export default function Hero() {
  return (
    <section className="relative overflow-hidden bg-canvas">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(52% 48% at 62% 4%, rgba(22,82,240,0.07) 0%, transparent 60%), radial-gradient(34% 30% at 12% 46%, rgba(22,82,240,0.05) 0%, transparent 60%)",
        }}
      />

      <div className="relative mx-auto max-w-6xl px-6 pt-40 pb-24 text-center">
        <p className="mx-auto mb-7 inline-flex items-center gap-2 rounded-full border border-line bg-white px-4 py-1.5 text-xs font-medium tracking-wide text-ink/70">
          Where B2B brands work with creators
        </p>

        <h1 className="mx-auto max-w-4xl text-balance font-display text-[clamp(44px,6vw,77px)] font-semibold leading-[1.04] tracking-[-0.04em] text-ink">
          The B2B LinkedIn
          <br />
          <span className="text-ink/45">Creator Marketplace.</span>
        </h1>

        <p className="mx-auto mt-7 max-w-2xl text-balance text-[19px] leading-relaxed text-[#43454c] sm:text-[21px] sm:leading-[1.55]">
          Find the creators your buyers already trust, launch campaigns in days,
          and track the clicks, leads and pipeline generated by every post.
        </p>

        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link
            href="/register"
            className="btn-primary w-full px-7 py-3 text-[15px] font-semibold sm:w-auto"
          >
            Launch a campaign
          </Link>
          <Link
            href="/#how-it-works"
            className="btn-light w-full px-7 py-3 text-[15px] font-semibold sm:w-auto"
          >
            See how Naano works
          </Link>
        </div>

        <div className="mx-auto mt-16 max-w-4xl pb-2">
          <p className="mb-6 text-xs font-medium uppercase tracking-[0.18em] text-ink-soft">
            Trusted by modern B2B teams
          </p>
          <LogoMarquee />
        </div>
      </div>
    </section>
  );
}