import Link from "next/link";
import LogoMarquee from "@/components/LogoMarquee";

export default function Hero() {
  return (
    <section className="relative overflow-hidden bg-night text-white">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(58% 55% at 50% 0%, rgba(37,99,235,0.28) 0%, transparent 62%), radial-gradient(34% 30% at 18% 42%, rgba(59,130,246,0.16) 0%, transparent 60%), radial-gradient(40% 36% at 85% 55%, rgba(30,64,175,0.22) 0%, transparent 62%)",
        }}
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 bottom-0 h-40"
        style={{
          background: "linear-gradient(to top, rgba(252,252,251,1), transparent)",
        }}
      />

      <div className="relative mx-auto max-w-6xl px-6 pt-36 pb-24 text-center">
        <p className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-4 py-1.5 text-xs font-medium tracking-wide text-white/70">
          Where B2B brands work with creators
        </p>

        <h1 className="mx-auto max-w-3xl text-balance font-display text-5xl font-bold leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">
          The B2B LinkedIn
          <br />
          <span className="text-white/45">Creator Marketplace.</span>
        </h1>

        <p className="mx-auto mt-6 max-w-xl text-balance text-base leading-relaxed text-white/60 sm:text-lg">
          Find the creators your buyers already trust, launch campaigns in days,
          and track the clicks, leads and pipeline generated by every post.
        </p>

        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link
            href="/register"
            className="btn-blue w-full px-7 py-3.5 text-[15px] font-semibold sm:w-auto"
          >
            Launch a campaign
          </Link>
          <Link
            href="/#how-it-works"
            className="btn w-full border border-white/20 bg-white/5 px-7 py-3.5 text-[15px] font-medium text-white backdrop-blur transition hover:bg-white/10 sm:w-auto"
          >
            See how Naano works
          </Link>
        </div>

        <div className="mx-auto mt-16 max-w-4xl pb-2">
          <p className="mb-6 text-xs font-medium uppercase tracking-[0.18em] text-white/40">
            Trusted by modern B2B teams
          </p>
          <LogoMarquee dark />
        </div>
      </div>
    </section>
  );
}