import type { Creator, Campaign } from "@/lib/types";

export const creators: Creator[] = [
  {
    id: "c1",
    slug: "thomas-higadere",
    name: "Thomas Higadère",
    firstName: "Thomas",
    headline: "B2B & AI · 34K followers",
    bio: "How AI changed our prospecting workflow for wealth managers and private bankers. Ex-growth lead building GTM systems.",
    role: "AI & SaaS creator",
    follows: 34000,
    networks: ["LinkedIn"],
    price: 850,
    fit: 92,
    countries: ["France", "EU"],
    topics: ["AI", "SaaS", "GTM", "Fintech"],
    status: "active",
    rating: 4.8,
    color: "from-blue-500 to-indigo-600",
    posts: [
      {
        title: "How AI changed our prospecting workflow for wealth managers and private bankers.",
        impressions: 42800,
        clicks: 312,
        leads: 18,
        brand: "lemlist",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c2",
    slug: "robin-tempe",
    name: "Robin Tempe",
    firstName: "Robin",
    headline: "Sales & AI · 12K followers",
    bio: "I run my entire prospecting workflow through an AI. Here is how. Operator of sales systems, ex-AE turned coach.",
    role: "Sales & AI creator",
    follows: 12000,
    networks: ["LinkedIn"],
    price: 500,
    fit: 88,
    countries: ["France", "EU"],
    topics: ["Sales", "AI", "Prospecting"],
    status: "active",
    rating: 4.9,
    color: "from-emerald-500 to-teal-600",
    posts: [
      {
        title: "I run my entire prospecting workflow through an AI. Here is how.",
        impressions: 9000,
        clicks: 100,
        leads: 50,
        brand: "Leadbay",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c3",
    slug: "eric-djavid",
    name: "Eric Djavid",
    firstName: "Eric",
    headline: "Sales Leader · B2B · 40K followers",
    bio: "Most sales teams spend 80% of their time on the wrong leads. Here is how I changed that.",
    role: "Sales leader",
    follows: 40000,
    networks: ["LinkedIn", "X"],
    price: 1200,
    fit: 86,
    countries: ["France", "Global"],
    topics: ["Sales", "B2B", "Revenue"],
    status: "active",
    rating: 4.7,
    color: "from-rose-500 to-pink-600",
    posts: [
      {
        title: "Most sales teams spend 80% of their time on the wrong leads. Here is how I changed that.",
        impressions: 20000,
        clicks: 350,
        leads: 80,
        brand: "Leadbay",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c4",
    slug: "marina-panova",
    name: "Marina Panova",
    firstName: "Marina",
    headline: "Content Creator · B2B · 34K followers",
    bio: "How I build my 30-day LinkedIn content system, the exact playbook.",
    role: "Content creator",
    follows: 34000,
    networks: ["LinkedIn"],
    price: 700,
    fit: 90,
    countries: ["UK", "Global"],
    topics: ["B2B", "Content", "Personal branding"],
    status: "active",
    rating: 4.9,
    color: "from-amber-500 to-orange-600",
    posts: [
      {
        title: "How I build my 30-day LinkedIn content system, the exact playbook.",
        impressions: 100000,
        clicks: 1600,
        leads: 320,
        brand: "Abyssale",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c5",
    slug: "aya-benali",
    name: "Aya Benali",
    firstName: "Aya",
    headline: "Founders · GTM teams · 98K followers",
    bio: "Deep voice for founder-led distribution. I help GTM teams turn engineering into stories buyers retell.",
    role: "Founders & GTM creator",
    follows: 98000,
    networks: ["LinkedIn", "X", "YouTube"],
    price: 3000,
    fit: 84,
    countries: ["France", "Global"],
    topics: ["Founders", "GTM", "DevTools"],
    status: "invite-only",
    rating: 4.6,
    color: "from-violet-500 to-purple-600",
    posts: [
      {
        title: "The GTM playbook nobody teaches founders.",
        impressions: 60000,
        clicks: 940,
        leads: 210,
        brand: "Attio",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c6",
    slug: "raphael-dubois",
    name: "Raphaël Dubois",
    firstName: "Raphaël",
    headline: "RevOps · SaaS · 22K followers",
    bio: "Revenue operations nerd. I break down the systems behind predictable B2B pipelines.",
    role: "RevOps creator",
    follows: 22000,
    networks: ["LinkedIn"],
    price: 600,
    fit: 82,
    countries: ["France", "EU"],
    topics: ["RevOps", "SaaS", "Pricing"],
    status: "active",
    rating: 4.8,
    color: "from-cyan-500 to-sky-600",
    posts: [
      {
        title: "Why most RevOps teams fail at pricing.",
        impressions: 31000,
        clicks: 420,
        leads: 64,
        brand: "Ringover",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c7",
    slug: "nada-khalil",
    name: "Nada Khalil",
    firstName: "Nada",
    headline: "Product-led growth · 46K followers",
    bio: "I write about product-led growth and the hidden loops behind consumer-grade SaaS.",
    role: "PLG creator",
    follows: 46000,
    networks: ["LinkedIn", "X"],
    price: 1400,
    fit: 79,
    countries: ["UAE", "Global"],
    topics: ["PLG", "Product", "SaaS"],
    status: "active",
    rating: 4.7,
    color: "from-lime-500 to-green-600",
    posts: [
      {
        title: "The activation loop every PLG startup forgets.",
        impressions: 52000,
        clicks: 780,
        leads: 132,
        brand: "Folk",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c8",
    slug: "david-costa",
    name: "David Costa",
    firstName: "David",
    headline: "DevTools · Open-source · 18K followers",
    bio: "Staff engineer writing about DX, open-source economics and the tooling wars.",
    role: "DevTools creator",
    follows: 18000,
    networks: ["X", "YouTube"],
    price: 650,
    fit: 76,
    countries: ["Portugal", "EU"],
    topics: ["DevTools", "Open-source", "AI"],
    status: "active",
    rating: 4.6,
    color: "from-fuchsia-500 to-pink-600",
    posts: [
      {
        title: "Open-source is eating the AI stack, pay attention.",
        impressions: 74000,
        clicks: 1100,
        leads: 88,
        brand: "Folk",
        url: "https://x.com/",
      },
    ],
  },
  {
    id: "c9",
    slug: "sofia-nguyen",
    name: "Sofia Nguyen",
    firstName: "Sofia",
    headline: "HR tech · People ops · 9K followers",
    bio: "People ops leader sharing the messy reality of building teams in scaling startups.",
    role: "HR tech creator",
    follows: 9000,
    networks: ["LinkedIn"],
    price: 350,
    fit: 81,
    countries: ["Singapore", "APAC"],
    topics: ["HR tech", "People ops", "Future of work"],
    status: "active",
    rating: 4.9,
    color: "from-teal-400 to-emerald-600",
    posts: [
      {
        title: "What nobody tells you about hiring in a down market.",
        impressions: 15000,
        clicks: 210,
        leads: 26,
        brand: "ChatSEO",
        url: "https://www.linkedin.com/",
      },
    ],
  },
  {
    id: "c10",
    slug: "lucas-weber",
    name: "Lucas Weber",
    firstName: "Lucas",
    headline: "Marketing · B2B · 27K followers",
    bio: "B2B marketer documenting experiments across demand gen, SEO and influencer-led growth.",
    role: "Marketing creator",
    follows: 27000,
    networks: ["LinkedIn", "YouTube"],
    price: 900,
    fit: 85,
    countries: ["Germany", "EU"],
    topics: ["Marketing", "SEO", "Demand gen"],
    status: "active",
    rating: 4.8,
    color: "from-orange-400 to-rose-500",
    posts: [
      {
        title: "SEO is dead, long live search everywhere.",
        impressions: 88000,
        clicks: 1500,
        leads: 240,
        brand: "BlogSEO",
        url: "https://www.linkedin.com/",
      },
    ],
  },
];

export const marketplaceCreators = creators;

export const defaultCampaigns: Campaign[] = [
  {
    id: "cmp-1",
    name: "SEO & SaaS trial launch",
    status: "live",
    objective: "Drive qualified trials for BlogSEO from creator audiences.",
    budget: 4250,
    startDate: "2026-08-18",
    endDate: "2026-09-18",
    keywords: ["SEO", "SaaS", "Content marketing"],
    trackingLink: "https://blogseo.io/?utm_source=naano&utm_medium=creator&utm_campaign=seo-trial",
    creators: [
      { creatorId: "c10", state: "approved" },
      { creatorId: "c4", state: "live" },
      { creatorId: "c1", state: "live" },
    ],
    metrics: {
      impressions: 152000,
      clicks: 2940,
      leads: 512,
      pipeline: 48200,
      cost: 2450,
    },
  },
  {
    id: "cmp-2",
    name: "Prospecting workflows — Q3",
    status: "briefing",
    objective: "Position Leadbay as the home for AI-powered prospecting.",
    budget: 2300,
    startDate: "2026-09-25",
    endDate: "2026-10-25",
    keywords: ["Sales", "AI", "Prospecting"],
    trackingLink: "https://leadbay.ai/?ref=naano",
    creators: [
      { creatorId: "c3", state: "draft" },
      { creatorId: "c2", state: "invited" },
      { creatorId: "c7", state: "invited" },
    ],
  },
  {
    id: "cmp-3",
    name: "Autumn PLG push",
    status: "draft",
    objective: "New product-adjacent awareness for the CRM for creators.",
    budget: 3000,
    startDate: "2026-10-05",
    endDate: "2026-11-05",
    keywords: ["PLG", "CRM", "Creators"],
    trackingLink: "",
    creators: [],
  },
];

export function getCreator(id: string) {
  return creators.find((c) => c.id === id);
}

export function getCampaign(id: string) {
  return defaultCampaigns.find((c) => c.id === id);
}

export const formatEuro = (n: number) =>
  new Intl.NumberFormat("en-IE", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(n);

export const formatCompact = (n: number) =>
  new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(n);